spring:
  main:
    web-application-type: reactive
  application:
    name: @project.name@
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: https://myhost.net/oauth2/mau/connect/jwk_uri

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
    #level: "{\"time\":\"%d{dd MMM E HH:mm:ss.SSS}\", \"TraceId\":\"%X{traceId:-}\", \"SpanId\":\"%X{spanId:-}\", \"source\":\"%logger{35}:%L\", \"level\":\"%-5level\", \"message\":\"%replace(%m%wEx{6}){'[\r\n]+', '\\n'}%nopex\"}%n"
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, metrics
  metrics:
#    enable:
#      http:
#        client:
#          requests: false
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint:

server:
  error:
    include-message: always