{
 "title": "springboot-observability",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "GreetingService_greeting_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(GreetingService_greeting_seconds_count[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GreetingService.greeting.HIGH",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(GreetingService_greeting_seconds_count{latency=\"high\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "hello/{name}",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri=\"/hello/{name}\", method=\"GET\", status=\"200\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GreetingService.greeting.LOW",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(GreetingService_greeting_seconds_count{latency=\"low\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}